### ISSUE TITLE
Add versioning to misk.jobqueue.Job

### ISSUE THREAD

**Issue by minostro** [cashapp/misk#1530]
## Error Scenario

There is a race condition when deploying a new version of the application. The situation is:

1. A new version of the app will enqueue a job.
2. An already running (old version) of the app (job handler), which hasn't been killed by the deployment process yet, will attempt to process the event potentially causing issues. Assume that the job signature hasn't changed at all. The issue is more related with the business logic that the job handler implements.

## Proposal: Adding versioning to `misk.jobqueue.Job`

A version in the Job (attributes) would help JobHandlers know if they are allowed to process a given Job. Otherwise, they would put the message back in the queue. 

There are different things we can use as a message version (in order of preference): 
* Image creation timestamp: We would need the expose these somehow to the application.
* Git Sha: consumers would have some awareness of the git repository to know if the SHA is included in the current deploy.
* A manual version defined by application owners: Delegate this responsibility to application owners. However, if this is not automated is likely to be forgotten.

**Comment by ryanhall07** [comment]
this seems specific to the schema of the job payload. why can't you add a version there?

**Comment by minostro** [comment]
We could do that. In fact, that's the last bullet of the proposal section in this issue. However, we were wondering if this could be somewhat automated; manually adding a version seems brittle specially when there is no change on the job payload structure, but rather how job handlers process the jobs.

**Comment by biasedbit** [comment]
If the structure hasn't changed and the old (possibly bugged) handler is capable of executing the job, broken business logic will eventually become fixed as the rollout completes. If the goal is to immediately avoid execution of any further broken logic, there are other levers we can use to halt consumption until new, fixed hosts are rolled out.

Of the three proposed options, I'd strongly lean on manual versioning — and at that point, I agree w/ Ryan; this can/should be app/handler specific.

Curious about the issues you encountered, would you mind elaborating?

**Comment by frojasg** [comment]
Why do you lean on manual versioning? I see this option as unreliable because we need to update something to avoid this case manually, and it is likely to be forgotten. 

Yes, there are other ways to avoid this scenario. We could have a different cluster for job handler, and making sure we deploy that cluster before producers.

We're trying to avoid needing to think about versioning on the consumer side to avoid error scenarios (even if they're transient).

**Comment by minostro** [comment]
> Curious about the issues you encountered, would you mind elaborating?

evently = a service that produces events.
invest-flow = the service that consume events.

The data flow is as follows:
a. evently delivers an event
b. invest-flow creates a business object (an order, a customer, etc)
c. invest-flow enqueues a sqs job
d. invest-flow job handler picks the message and implement some business logic.

What happened was:
1. deploy started
2. `pod1` subscribed to a new evently topic and it executed a.
3. `pod1` received an evently event --so it executes b. and c.
4. `pod2` executed d. --this is an old pod that has the old business logic (buggy business logic, or business logic that does not know how to handle the newly published job).

This error is a transient error because sqs job will retry, so hopefully at time of retry, `pod2` is gone. It's worth noting that in this case the job payload has a `type` attr on it. `pod2` only knows how to handle jobs of one type. `pod1` knows how to handle jobs with two types.

**Comment by ryanhall07** [comment]
Still not sure I understand the benefit of a version. Let's assume for the sake of argument that a version allows a Handler to decide if they can process an event. What does the handler do? It would just ignore the job and let another handler retry it later. How is that any different from what happened without a version? It's a more graceful error? While maybe that's a slight improvement to the error handling, you still have degraded job processing.

Personally as a developer I'd rather make my handlers backwards compatible so there is no disruption to my job handling processing. Old code can process new jobs for at least one release. I think we should encourage practices that increase job throughput.

**Comment by frojasg** [comment]
The intent behind this proposal is to reduce the burden on application developers to build forward-compatible handlers. 

The use of versioning seemed like a seamless way to handle this. However, we agree it has some negative impact on job throughput. Also, it could be harmful in rollback scenarios. 

We also thought about changing our infrastructure split job handlers and producers in different clusters so that we can deploy them independently. However, it's not easy to draw a line to split them, especially in this case where the producer was an event handler. 

Based on this analysis, we agreed that it's not good to hide this complexity from developers, and we should encourage best practices on forward-compatibility and increasing the job throughput.  So I'm closing this proposal.
